OTS/urls.py
from django.urls import path
from OTS.views import *
app_name='OTS'

urlpatterns = [
    path('',welcome),
    path('new-candidate',CandidateRegistrationForm,name='registrationfrom'),
    path('store-candiadate',CandidateRegistration,name='storecandidate'),
    path('login',loginview,name='login'),
    path('home',CandidateHome,name='home'),
    path('test-papper',Testpapper,name="testpapper"),
    path('calculate-result',CalculateTestResult,name='calculatetest'),
    path('test-history',TestHistory,name="testHistory"),
    path('result',ShowTestResult,name='result'),
    path('logout',loginview,name='logout'),
    
   
]

examapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('OTS/',include('OTS.urls')),
]

OTS/models.py
from django.db import models

# data base full deisign page....

class Candidate(models.Model):
    username=models.CharField(primary_key=True,max_length=20)
    password=models.CharField(null=False,max_length=20)
    name=models.CharField(null=False,max_length=30)
    test_attempted=models.IntegerField(default=0)
    points=models.FloatField(default=0.0)
    

class Question(models.Model):
    qid=models.BigAutoField(primary_key=True,auto_created=True)
    que=models.TextField()
    a=models.CharField(max_length=255)
    b=models.CharField(max_length=255)
    c=models.CharField(max_length=255)
    d=models.CharField(max_length=255)
    ans=models.CharField(max_length=2)
    
    
class Result(models.Model):
    resultid=models.BigAutoField(primary_key=True,auto_created=True)
    username=models.ForeignKey(Candidate,on_delete=models.CASCADE)
    date=models.DateField(auto_now=True)
    time=models.TimeField(auto_now=True)
    attempt=models.IntegerField()
    right=models.IntegerField()
    wrong=models.IntegerField()
    points=models.FloatField()
    
    
        
        

OTS/views.py
from django.shortcuts import render
from django.http import HttpResponse,HttpResponseRedirect
from OTS.models import *
from django.template import loader
import random

def welcome(request):
    template=loader.get_template('welcome.html')
    return HttpResponse(template.render())

def CandidateRegistrationForm(request):
    res=render(request,'register.html')
    return res

def CandidateRegistration(request):
    if request.method=='POST':
        username=request.POST['username']
        # check if the user exists
        if(len(Candidate.objects.filter(username=username))):
            userstatus=1
            
        else:
            candidate=Candidate()
            candidate.username=username
            candidate.password=request.POST['password']
            candidate.name=request.POST['name']
            candidate.save()
            userstatus=2
            
    else:
        userstatus=3  # method not post
        
    context={
        'userstatus':userstatus
    }
    
    res=render(request,'registration.html',context)
    return res
             
           

def loginview(request):
    if request.method=='POST':
        username=request.POST['username']
        password=request.POST['password']
        candidate=Candidate.objects.filter(username=username,password=password)
        if len(candidate)==0:
            loginerror="INVALID CREDENTIALS"
            res=render(request,'login.html',{'loginerror':loginerror})
            
        else:
            request.session['username']=candidate[0].username
            request.session['name']=candidate[0].name
            res=HttpResponseRedirect("home")
    else:       
        res=render(request,'login.html')
    return res
    
 
def CandidateHome(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
    else:
        res=render(request,'home.html')
        return res
    
    
    
def Testpapper(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
        
    n=int(request.GET['n'])
    questions_pool=list(Question.objects.all())
    random.shuffle(questions_pool)
    question_list=questions_pool[:n]
    context={'questions':question_list}
    res=render(request,'testpapper.html',context)
    return res

def CalculateTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
        
    total_attempt=0
    total_right=0
    total_wrong=0
    qid_list=[]
    
    for k in request.POST:
        if k.startswith('qno'):
            qid_list.append(int (request.POST[k]))
    
    
    for n in qid_list:
        question=Question.objects.get(qid=n)
        try:
            if question.ans==request.POST['q'+str(n)]:
                total_right+=1
            else:
                total_wrong+=1
            total_attempt+=1
        except:
            pass
    
    
    points=(total_right-total_wrong)/len(qid_list)*10
    
    result=Result()
    result.username=Candidate.objects.get(username=request.session['username'])
    result.attempt=total_attempt
    result.right=total_right
    result.wrong=total_wrong
    result.points=points
    result.save()
    
    candidate=Candidate.objects.get(username=request.session['username'])
    candidate.test_attempted+=1
    candidate.points=(candidate.points*(candidate.test_attempted-1)+points)/candidate.test_attempted
    candidate.save()
    
    return HttpResponseRedirect('result')
                        
        

def TestHistory(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
        
    candidate=Candidate.objects.filter(username=request.session['username'])
    results=Result.objects.filter(username_id=candidate[0].username)
    
    context={'candidate':candidate[0],'results':results}
    res=render(request,'candidate_history.html',context)
    return res

def ShowTestResult(request):
    if 'name' not in request.session.keys():
        res=HttpResponseRedirect("login")
        
    result=Result.objects.filter(resultid=Result.objects.latest('resultid').resultid,username_id=request.session['username'])
    context={
        'result':result
    } 
    
    res=render(request,'show_result.html',context)
    return res

def logoutView(request):
   if 'name' in request.session.keys():
       del request.session['username']
       del request.session['name']
       return HttpResponseRedirect("login") 

    

OTS/templates/Register.html
{% extends 'main.html' %}


{%block title%} OTS Registration Form {%endblock title%}


{%block top%}

<a href="{% url 'OTS:login' %}">Login</a>
{% endblock %}

{% block content%}

<div class="all-forms">
   <form action="{%url 'OTS:storecandidate'%}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <label for="name">Name</label>
    <input type="text" name="name">


    <input type="Submit" value="Submit">
    <input type="reset" value="Clear">


</form>
Already Have An Account, <a href="{%url 'OTS:login'%}">Click Here,</a>
</div>

{%endblock%}

OTS/templates/candidate_history.html
{% extends 'main.html' %}

{%block title%} OTS - Candidate History {%endblock title%}


{%block top%}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock %}

{% block content%}

<h1>Your Report Card</h1>
 <h3><p>Hi, <i>{{candidate.name}} </i> you have attempted total {{candidate.test_attempted}} tests and you have scored= {{candidate.points}} on the Scale of 10</p></h3>


<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>

    {% for r in results %}
    <tr>
        <td>{{r.date}}</td>
        <td> {{r.time}}</td>
        <td> {{r.attempt}}</td>
        <td>{{r.right}} </td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
       
    </tr>
    {% endfor %}

</table>
{%endblock%}

OTS/templates/home.html
{% extends 'main.html' %}

{%block title%} OTS Candidate Home Page {%endblock title%}


{%block top%}
<a href="{% url 'OTS:home' %}">Sign Up</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock %}

{% block content%}

<h1>Welcome  {{request.session.name}},to your Home Page</h1>
<div class="button-link">
    <a href="{% url 'OTS:testpapper' %}?n=1">Test of 1 Question</a>
</div>

<div class="button-link">
    <a href="{% url 'OTS:testpapper' %}?n=3">Test of 3 Question</a>
</div>

<div class="button-link">
    <a href="{% url 'OTS:testpapper' %}?n=5">Test of 5 Question</a>
</div>

<div class="button-link">
    <a href="{% url 'OTS:testHistory' %}">Test History</a>
</div>

{%endblock%}

OTS/templates/login.html
{% extends 'main.html' %}

{%block title%} OTS Login Form {%endblock title%}


{%block top%}
<a href="{% url 'OTS:registrationfrom' %}">Sign Up</a>

{% endblock %}

{% block content%}

<div class="all-forms">

    {% if loginerror %}

    <div id="error">INVALID Login Error</div>

    {% endif %}
  <form action="{% url 'OTS:login' %}" method="POST">
   {% csrf_token %}

   <div class="form-unit">

    <label for="username">Username</label>
    <input type="text" name="username">

   </div>


   <div class="form-unit">

    <label for="password">Password</label>
    <input type="password" name="password">

   </div>


   <div class="form-unit">

   
    <input type="submit" value="Login">
    <input type="reset" value="Clear">

   </div>


  </form>


  New User <a href="{% url 'OTS:registrationfrom' %}"> Click Here</a>
</div>
{%endblock%}

OTS/templates/main.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>

    <link rel="stylesheet" href="{% static 'theme.css'%}">
    <link rel="stylesheet" href="{% static 'formstyle.css'%}">
    <link rel="stylesheet" href="{% static 'buttonstyle.css'%}">
</head>
<body>
    <div class="top">
        <div class="site name"><h1>Online Testing System</h1></div>
        <div class="menu">
            {% block top %} {% endblock %}
        </div>
    </div>

    <div class="content">
        {% block content %} {% endblock %}
    </div>
</body>
</html>

OTS/templates/register.html
{% extends 'main.html' %}


{%block title%} OTS Registration Form {%endblock title%}


{%block top%}

<a href="{% url 'OTS:login' %}">Login</a>
{% endblock %}

{% block content%}

<div class="all-forms">
   <form action="{%url 'OTS:storecandidate'%}" method="post">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" name="username">

    <label for="password">Password</label>
    <input type="password" name="password">

    <label for="name">Name</label>
    <input type="text" name="name">


    <input type="Submit" value="Submit">
    <input type="reset" value="Clear">


</form>
Already Have An Account, <a href="{%url 'OTS:login'%}">Click Here,</a>
</div>

{%endblock%}

OTS/templates/registration.html
{% extends 'main.html' %}

{%block title%} OTS Registration Status {%endblock title%}


{%block top%}
<a href="{% url 'OTS:registrationfrom' %}">Sign Up</a>
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock %}

{% block content%}

{% if userstatus == 1 %}
  <div class="userstatus">
    <h2>Sorry,username already exists please try Different username.</h2>

    <a href="{% url 'OTS:registrationfrom' %}">Back To Register form</a>
  </div>

{% elif userstatus == 2 %}
  
<div class="userstatus">
    <h2>Congratulations, USerCreated Successfully..!!!!!<h2>
    <a href="{% url 'OTS:login' %}">Login</a>
</div>

{% elif userstatus == 3 %}
  
<div class="userstatus">
   Oops.. Improper Request
   <a href="{% url 'OTS:registrationfrom' %}">Back To Register form</a>
</div>

{% endif%}
{%endblock%}

OTS/templates/show_result.html
{% extends 'main.html' %}

{%block title%} OTS- Your Test Result {%endblock title%}


{%block top%}
<a href="{% url 'OTS:home' %}">Home</a>
<a href="{% url 'OTS:logout' %}">Logout</a>
{% endblock %}

{% block content%}

<table>
    <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Attempt</th>
        <th>Right</th>
        <th>Wrong</th>
        <th>Points</th>
    </tr>

    {% for r in result %}
    <tr>
        <td>{{r.date}}</td>
        <td> {{r.time}}</td>
        <td> {{r.attempt}}</td>
        <td>{{r.right}} </td>
        <td>{{r.wrong}}</td>
        <td>{{r.points}}</td>
       
    </tr>
    {% endfor %}

</table>

{%endblock%}

OTS/templates/testpapper.html
{% extends 'main.html' %}

{%block title%} OTS Test Papper {%endblock title%}


{%block top%}

{% endblock %}

{% block content%}

<form action="{% url 'OTS:calculatetest' %}" method="post">
    {% csrf_token %}
    {% for question in questions%}

    <div class="question">
        <h4>  <input type="hidden" name="qno{{question.qid}}" value="{{question.qid}}">
          {{question.que}}

        </h4>
    </div>

    <div class="options"><input type="radio" name="q{{question.qid}}" value="a"> {{question.a}} </div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="b"> {{question.b}} </div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="c"> {{question.c}} </div>
    <div class="options"><input type="radio" name="q{{question.qid}}" value="d"> {{question.d}} </div>

    {%endfor%}

  <div id="abc">

    <input type="submit" value="submit">
  </div>


</form>
{%endblock%}

OTS/templates/welcome.html
{% extends 'main.html' %}

{%block title%} Welcome to Online Testing System {%endblock title%}


{%block top%}
<a href="{% url 'OTS:registrationfrom' %}">Sign Up</a>
<a href="{% url 'OTS:login' %}">Login</a>
{% endblock %}

{% block content%}

<h2>
<p><i>Welcome to our online testing app, your go-to destination for honing your coding skills and acing your next interview! Our home page is designed to empower aspiring developers like you with a curated collection of challenging coding interview questions. Whether you're gearing up for a job interview or simply want to enhance your programming prowess, our extensive question bank covers a variety of topics and difficulty levels. From algorithms and data structures to problem-solving and language-specific challenges, we've got you covered. Elevate your coding journey, track your progress, and prepare for success with our user-friendly interface. Embrace the thrill of coding and unleash your potential – start your journey on our home page today!  </p>
</h2>
<P>
    <h4>HERE YOU CAN PRACTISE VARIOUS TOPICS<BR><BR>

        1.DATA STRUCTURES AND ALGORITHMS<BR>
        2.OBJECT ORIENTED QUESTIONS<BR>
        3.AND MANY MORE...

    </h4>
</p>
<br>

<h3><p>............................LOGIN AND START PRPEPARING FOR YOUR UPCOMING INTERVIEWS............................</P></h3>
 <BR>
    <BR>
        <BR>


    <H3><P> ..!!!  OUR BEST WISHES IS WITH YOU FOR YOUR UPCOMING INTERVIEW  ..!!!</p></H3>

        <P>
        
            

             Made By ,  Aslaan Khan.....
        </p>
{%endblock%}